### ISSUE TITLE
VI Description unreadable in "Build Message with Arguments(Auto Check)"

### ISSUE THREAD

**Issue by drjdpowell** [NEVSTOP-LAB/Communicable-State-Machine#348]
![image](https://github.com/user-attachments/assets/43ad4f4a-b8da-4fa9-919c-f22e76641859)

**Comment by nevstop** [comment]
@drjdpowell I moved this issue to the CSM core repository, as it seems more appropriate there. it will be fixed in the upcoming December release.

As a heavy user of your SQLite/JSONText/CycleTableProbe library, I am delighted to see your interest in CSM. Please feel free to leave your suggestion and feedback. It will be valuable for me. :)

**Comment by nevstop** [comment]
add a testcase for checking documentation.
